// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.2
// source: api/schema/user_stream/user_stream.proto

package user_stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNKNOWN  Action = 0
	Action_ACTION_CREATED  Action = 1
	Action_ACTION_MODIFIED Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_CREATED",
		2: "ACTION_MODIFIED",
	}
	Action_value = map[string]int32{
		"ACTION_UNKNOWN":  0,
		"ACTION_CREATED":  1,
		"ACTION_MODIFIED": 2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_schema_user_stream_user_stream_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_api_schema_user_stream_user_stream_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_api_schema_user_stream_user_stream_proto_rawDescGZIP(), []int{0}
}

type UserStreamV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action         Action `protobuf:"varint,1,opt,name=action,proto3,enum=user_stream.Action" json:"action,omitempty"`
	PublicId       string `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role           string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Timestamp      int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *UserStreamV1) Reset() {
	*x = UserStreamV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_schema_user_stream_user_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStreamV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStreamV1) ProtoMessage() {}

func (x *UserStreamV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_schema_user_stream_user_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStreamV1.ProtoReflect.Descriptor instead.
func (*UserStreamV1) Descriptor() ([]byte, []int) {
	return file_api_schema_user_stream_user_stream_proto_rawDescGZIP(), []int{0}
}

func (x *UserStreamV1) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNKNOWN
}

func (x *UserStreamV1) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UserStreamV1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserStreamV1) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserStreamV1) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *UserStreamV1) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_schema_user_stream_user_stream_proto protoreflect.FileDescriptor

var file_api_schema_user_stream_user_stream_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0xc7, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x12, 0x2b, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64,
	0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2a, 0x45, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x4f,
	0x44, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x02, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x72, 0x6d, 0x6e, 0x74, 0x2f, 0x41, 0x41, 0x36,
	0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_schema_user_stream_user_stream_proto_rawDescOnce sync.Once
	file_api_schema_user_stream_user_stream_proto_rawDescData = file_api_schema_user_stream_user_stream_proto_rawDesc
)

func file_api_schema_user_stream_user_stream_proto_rawDescGZIP() []byte {
	file_api_schema_user_stream_user_stream_proto_rawDescOnce.Do(func() {
		file_api_schema_user_stream_user_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_schema_user_stream_user_stream_proto_rawDescData)
	})
	return file_api_schema_user_stream_user_stream_proto_rawDescData
}

var file_api_schema_user_stream_user_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_schema_user_stream_user_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_schema_user_stream_user_stream_proto_goTypes = []interface{}{
	(Action)(0),          // 0: user_stream.Action
	(*UserStreamV1)(nil), // 1: user_stream.UserStreamV1
}
var file_api_schema_user_stream_user_stream_proto_depIdxs = []int32{
	0, // 0: user_stream.UserStreamV1.action:type_name -> user_stream.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_schema_user_stream_user_stream_proto_init() }
func file_api_schema_user_stream_user_stream_proto_init() {
	if File_api_schema_user_stream_user_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_schema_user_stream_user_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStreamV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_schema_user_stream_user_stream_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_schema_user_stream_user_stream_proto_goTypes,
		DependencyIndexes: file_api_schema_user_stream_user_stream_proto_depIdxs,
		EnumInfos:         file_api_schema_user_stream_user_stream_proto_enumTypes,
		MessageInfos:      file_api_schema_user_stream_user_stream_proto_msgTypes,
	}.Build()
	File_api_schema_user_stream_user_stream_proto = out.File
	file_api_schema_user_stream_user_stream_proto_rawDesc = nil
	file_api_schema_user_stream_user_stream_proto_goTypes = nil
	file_api_schema_user_stream_user_stream_proto_depIdxs = nil
}
