// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.25.2
// source: api/schema/task_stream/task_stream.proto

package task_stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNKNOWN  Action = 0
	Action_ACTION_CREATED  Action = 1
	Action_ACTION_MODIFIED Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_CREATED",
		2: "ACTION_MODIFIED",
	}
	Action_value = map[string]int32{
		"ACTION_UNKNOWN":  0,
		"ACTION_CREATED":  1,
		"ACTION_MODIFIED": 2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_schema_task_stream_task_stream_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_api_schema_task_stream_task_stream_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_api_schema_task_stream_task_stream_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNKNOWN     Status = 0
	Status_STATUS_TODO        Status = 1
	Status_STATUS_IN_PROGRESS Status = 2
	Status_STATUS_DONE        Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_TODO",
		2: "STATUS_IN_PROGRESS",
		3: "STATUS_DONE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":     0,
		"STATUS_TODO":        1,
		"STATUS_IN_PROGRESS": 2,
		"STATUS_DONE":        3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_schema_task_stream_task_stream_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_schema_task_stream_task_stream_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_schema_task_stream_task_stream_proto_rawDescGZIP(), []int{1}
}

type TaskStreamV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action         Action `protobuf:"varint,1,opt,name=action,proto3,enum=task_stream.Action" json:"action,omitempty"`
	Status         Status `protobuf:"varint,2,opt,name=status,proto3,enum=task_stream.Status" json:"status,omitempty"`
	PublicId       string `protobuf:"bytes,3,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Title          string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Cost           int64  `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	UserId         string `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdempotencyKey string `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Timestamp      int64  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	JiraId         string `protobuf:"bytes,10,opt,name=jira_id,json=jiraId,proto3" json:"jira_id,omitempty"`
}

func (x *TaskStreamV1) Reset() {
	*x = TaskStreamV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_schema_task_stream_task_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskStreamV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStreamV1) ProtoMessage() {}

func (x *TaskStreamV1) ProtoReflect() protoreflect.Message {
	mi := &file_api_schema_task_stream_task_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStreamV1.ProtoReflect.Descriptor instead.
func (*TaskStreamV1) Descriptor() ([]byte, []int) {
	return file_api_schema_task_stream_task_stream_proto_rawDescGZIP(), []int{0}
}

func (x *TaskStreamV1) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNKNOWN
}

func (x *TaskStreamV1) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *TaskStreamV1) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *TaskStreamV1) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskStreamV1) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskStreamV1) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *TaskStreamV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TaskStreamV1) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskStreamV1) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TaskStreamV1) GetJiraId() string {
	if x != nil {
		return x.JiraId
	}
	return ""
}

var File_api_schema_task_stream_task_stream_proto protoreflect.FileDescriptor

var file_api_schema_task_stream_task_stream_proto_rawDesc = []byte{
	0x0a, 0x28, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0xca, 0x02, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x31, 0x12, 0x2b, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65,
	0x6e, 0x63, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69,
	0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x6a,
	0x69, 0x72, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x69,
	0x72, 0x61, 0x49, 0x64, 0x2a, 0x45, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x0e, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x4d, 0x4f, 0x44, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x56, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x54, 0x4f, 0x44, 0x4f, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x4f, 0x4e,
	0x45, 0x10, 0x03, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x72, 0x6d, 0x6e, 0x74, 0x2f, 0x41, 0x41, 0x36, 0x5f, 0x68, 0x6f, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_schema_task_stream_task_stream_proto_rawDescOnce sync.Once
	file_api_schema_task_stream_task_stream_proto_rawDescData = file_api_schema_task_stream_task_stream_proto_rawDesc
)

func file_api_schema_task_stream_task_stream_proto_rawDescGZIP() []byte {
	file_api_schema_task_stream_task_stream_proto_rawDescOnce.Do(func() {
		file_api_schema_task_stream_task_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_schema_task_stream_task_stream_proto_rawDescData)
	})
	return file_api_schema_task_stream_task_stream_proto_rawDescData
}

var file_api_schema_task_stream_task_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_schema_task_stream_task_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_schema_task_stream_task_stream_proto_goTypes = []interface{}{
	(Action)(0),          // 0: task_stream.Action
	(Status)(0),          // 1: task_stream.Status
	(*TaskStreamV1)(nil), // 2: task_stream.TaskStreamV1
}
var file_api_schema_task_stream_task_stream_proto_depIdxs = []int32{
	0, // 0: task_stream.TaskStreamV1.action:type_name -> task_stream.Action
	1, // 1: task_stream.TaskStreamV1.status:type_name -> task_stream.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_schema_task_stream_task_stream_proto_init() }
func file_api_schema_task_stream_task_stream_proto_init() {
	if File_api_schema_task_stream_task_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_schema_task_stream_task_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskStreamV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_schema_task_stream_task_stream_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_schema_task_stream_task_stream_proto_goTypes,
		DependencyIndexes: file_api_schema_task_stream_task_stream_proto_depIdxs,
		EnumInfos:         file_api_schema_task_stream_task_stream_proto_enumTypes,
		MessageInfos:      file_api_schema_task_stream_task_stream_proto_msgTypes,
	}.Build()
	File_api_schema_task_stream_task_stream_proto = out.File
	file_api_schema_task_stream_task_stream_proto_rawDesc = nil
	file_api_schema_task_stream_task_stream_proto_goTypes = nil
	file_api_schema_task_stream_task_stream_proto_depIdxs = nil
}
