### Create roles 1
POST localhost:8091/roles?name=user
### 2
POST localhost:8091/roles?name=admin
### List roles
GET localhost:8091/roles

### Create users 1
POST localhost:8091/users?role=1&name=popug1
### 2
POST localhost:8091/users?role=1&name=popug2
### 3
POST localhost:8091/users?role=2&name=popug3
### List users
GET localhost:8091/users

### login as user
POST localhost:8091/login?user=popug1
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicHVibGljX2lkIjoiMDE4ZTI4Y2QtZTY3Mi03MzAwLWI0MjAtZGMwZWU3Njg4YjMwIiwibmFtZSI6InBvcHVnMSIsInJvbGUiOiJ1c2VyIn0.2LWDPKuUkpvgZY9VFY-qk_q8Hrnx0t88JIvGQJMH_O0

### login as admin
POST localhost:8091/login?user=popug3
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywicHVibGljX2lkIjoiMDE4ZTI4Y2UtNWJhNy03YTRkLThmYmQtODNhNTgzZGU4ZDc1IiwibmFtZSI6InBvcHVnMyIsInJvbGUiOiJhZG1pbiJ9.NK9VbFZgSCaRCi6nw7M5Mj1ErtiCNEdPG0Nkxd8NmSs

### Create task 1
POST localhost:8092/tasks?title=task1&description=descr
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicHVibGljX2lkIjoiMDE4ZTI4Y2QtZTY3Mi03MzAwLWI0MjAtZGMwZWU3Njg4YjMwIiwibmFtZSI6InBvcHVnMSIsInJvbGUiOiJ1c2VyIn0.2LWDPKuUkpvgZY9VFY-qk_q8Hrnx0t88JIvGQJMH_O0

### Make task done
POST localhost:8092/tasks/1?status=done
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicHVibGljX2lkIjoiMDE4ZTI4Y2QtZTY3Mi03MzAwLWI0MjAtZGMwZWU3Njg4YjMwIiwibmFtZSI6InBvcHVnMSIsInJvbGUiOiJ1c2VyIn0.2LWDPKuUkpvgZY9VFY-qk_q8Hrnx0t88JIvGQJMH_O0

### Reassign tasks
POST localhost:8092/reassign
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywicHVibGljX2lkIjoiMDE4ZTI4Y2UtNWJhNy03YTRkLThmYmQtODNhNTgzZGU4ZDc1IiwibmFtZSI6InBvcHVnMyIsInJvbGUiOiJhZG1pbiJ9.NK9VbFZgSCaRCi6nw7M5Mj1ErtiCNEdPG0Nkxd8NmSs

### Get user balance
GET localhost:8093/balance
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicHVibGljX2lkIjoiMDE4ZTI4Y2QtZTY3Mi03MzAwLWI0MjAtZGMwZWU3Njg4YjMwIiwibmFtZSI6InBvcHVnMSIsInJvbGUiOiJ1c2VyIn0.2LWDPKuUkpvgZY9VFY-qk_q8Hrnx0t88JIvGQJMH_O0

### Get user billing
GET localhost:8093/billing
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicHVibGljX2lkIjoiMDE4ZTI4Y2QtZTY3Mi03MzAwLWI0MjAtZGMwZWU3Njg4YjMwIiwibmFtZSI6InBvcHVnMSIsInJvbGUiOiJ1c2VyIn0.2LWDPKuUkpvgZY9VFY-qk_q8Hrnx0t88JIvGQJMH_O0

### Get user operations
GET localhost:8093/operations
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicHVibGljX2lkIjoiMDE4ZTI4Y2QtZTY3Mi03MzAwLWI0MjAtZGMwZWU3Njg4YjMwIiwibmFtZSI6InBvcHVnMSIsInJvbGUiOiJ1c2VyIn0.2LWDPKuUkpvgZY9VFY-qk_q8Hrnx0t88JIvGQJMH_O0

### Get admin billing stats
GET localhost:8093/stats
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywicHVibGljX2lkIjoiMDE4ZTI4Y2UtNWJhNy03YTRkLThmYmQtODNhNTgzZGU4ZDc1IiwibmFtZSI6InBvcHVnMyIsInJvbGUiOiJhZG1pbiJ9.NK9VbFZgSCaRCi6nw7M5Mj1ErtiCNEdPG0Nkxd8NmSs

### Get last day sum
GET localhost:8094/last_day_sum
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywicHVibGljX2lkIjoiMDE4ZTI4Y2UtNWJhNy03YTRkLThmYmQtODNhNTgzZGU4ZDc1IiwibmFtZSI6InBvcHVnMyIsInJvbGUiOiJhZG1pbiJ9.NK9VbFZgSCaRCi6nw7M5Mj1ErtiCNEdPG0Nkxd8NmSs

### Get last day popugs with debts count
GET localhost:8094/last_day_debts
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywicHVibGljX2lkIjoiMDE4ZTI4Y2UtNWJhNy03YTRkLThmYmQtODNhNTgzZGU4ZDc1IiwibmFtZSI6InBvcHVnMyIsInJvbGUiOiJhZG1pbiJ9.NK9VbFZgSCaRCi6nw7M5Mj1ErtiCNEdPG0Nkxd8NmSs

### Get highest price for period
GET localhost:8094/highest_price?from=2024-03-09&to=2024-03-11
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywicHVibGljX2lkIjoiMDE4ZTI4Y2UtNWJhNy03YTRkLThmYmQtODNhNTgzZGU4ZDc1IiwibmFtZSI6InBvcHVnMyIsInJvbGUiOiJhZG1pbiJ9.NK9VbFZgSCaRCi6nw7M5Mj1ErtiCNEdPG0Nkxd8NmSs