// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lrmnt/AA6_homework/billing/ent/billing"
	"github.com/lrmnt/AA6_homework/billing/ent/billingcycle"
	"github.com/lrmnt/AA6_homework/billing/ent/user"
)

// BillingCreate is the builder for creating a Billing entity.
type BillingCreate struct {
	config
	mutation *BillingMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (bc *BillingCreate) SetUUID(u uuid.UUID) *BillingCreate {
	bc.mutation.SetUUID(u)
	return bc
}

// SetAmount sets the "amount" field.
func (bc *BillingCreate) SetAmount(i int64) *BillingCreate {
	bc.mutation.SetAmount(i)
	return bc
}

// SetTimestamp sets the "timestamp" field.
func (bc *BillingCreate) SetTimestamp(i int64) *BillingCreate {
	bc.mutation.SetTimestamp(i)
	return bc
}

// SetType sets the "type" field.
func (bc *BillingCreate) SetType(b billing.Type) *BillingCreate {
	bc.mutation.SetType(b)
	return bc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (bc *BillingCreate) SetUserID(id int) *BillingCreate {
	bc.mutation.SetUserID(id)
	return bc
}

// SetUser sets the "user" edge to the User entity.
func (bc *BillingCreate) SetUser(u *User) *BillingCreate {
	return bc.SetUserID(u.ID)
}

// SetBillingCycleID sets the "billing_cycle" edge to the BillingCycle entity by ID.
func (bc *BillingCreate) SetBillingCycleID(id int) *BillingCreate {
	bc.mutation.SetBillingCycleID(id)
	return bc
}

// SetBillingCycle sets the "billing_cycle" edge to the BillingCycle entity.
func (bc *BillingCreate) SetBillingCycle(b *BillingCycle) *BillingCreate {
	return bc.SetBillingCycleID(b.ID)
}

// Mutation returns the BillingMutation object of the builder.
func (bc *BillingCreate) Mutation() *BillingMutation {
	return bc.mutation
}

// Save creates the Billing in the database.
func (bc *BillingCreate) Save(ctx context.Context) (*Billing, error) {
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BillingCreate) SaveX(ctx context.Context) *Billing {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BillingCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BillingCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BillingCreate) check() error {
	if _, ok := bc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "Billing.uuid"`)}
	}
	if _, ok := bc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Billing.amount"`)}
	}
	if _, ok := bc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "Billing.timestamp"`)}
	}
	if _, ok := bc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Billing.type"`)}
	}
	if v, ok := bc.mutation.GetType(); ok {
		if err := billing.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Billing.type": %w`, err)}
		}
	}
	if _, ok := bc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Billing.user"`)}
	}
	if _, ok := bc.mutation.BillingCycleID(); !ok {
		return &ValidationError{Name: "billing_cycle", err: errors.New(`ent: missing required edge "Billing.billing_cycle"`)}
	}
	return nil
}

func (bc *BillingCreate) sqlSave(ctx context.Context) (*Billing, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BillingCreate) createSpec() (*Billing, *sqlgraph.CreateSpec) {
	var (
		_node = &Billing{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(billing.Table, sqlgraph.NewFieldSpec(billing.FieldID, field.TypeInt))
	)
	if value, ok := bc.mutation.UUID(); ok {
		_spec.SetField(billing.FieldUUID, field.TypeUUID, value)
		_node.UUID = value
	}
	if value, ok := bc.mutation.Amount(); ok {
		_spec.SetField(billing.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := bc.mutation.Timestamp(); ok {
		_spec.SetField(billing.FieldTimestamp, field.TypeInt64, value)
		_node.Timestamp = value
	}
	if value, ok := bc.mutation.GetType(); ok {
		_spec.SetField(billing.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if nodes := bc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   billing.UserTable,
			Columns: []string{billing.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.billing_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.BillingCycleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   billing.BillingCycleTable,
			Columns: []string{billing.BillingCycleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(billingcycle.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.billing_billing_cycle = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BillingCreateBulk is the builder for creating many Billing entities in bulk.
type BillingCreateBulk struct {
	config
	err      error
	builders []*BillingCreate
}

// Save creates the Billing entities in the database.
func (bcb *BillingCreateBulk) Save(ctx context.Context) ([]*Billing, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Billing, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BillingCreateBulk) SaveX(ctx context.Context) []*Billing {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BillingCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BillingCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
