// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrmnt/AA6_homework/billing/ent/billing"
	"github.com/lrmnt/AA6_homework/billing/ent/billingcycle"
	"github.com/lrmnt/AA6_homework/billing/ent/predicate"
	"github.com/lrmnt/AA6_homework/billing/ent/user"
)

// BillingQuery is the builder for querying Billing entities.
type BillingQuery struct {
	config
	ctx              *QueryContext
	order            []billing.OrderOption
	inters           []Interceptor
	predicates       []predicate.Billing
	withUser         *UserQuery
	withBillingCycle *BillingCycleQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BillingQuery builder.
func (bq *BillingQuery) Where(ps ...predicate.Billing) *BillingQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BillingQuery) Limit(limit int) *BillingQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BillingQuery) Offset(offset int) *BillingQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BillingQuery) Unique(unique bool) *BillingQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BillingQuery) Order(o ...billing.OrderOption) *BillingQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryUser chains the current query on the "user" edge.
func (bq *BillingQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(billing.Table, billing.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, billing.UserTable, billing.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBillingCycle chains the current query on the "billing_cycle" edge.
func (bq *BillingQuery) QueryBillingCycle() *BillingCycleQuery {
	query := (&BillingCycleClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(billing.Table, billing.FieldID, selector),
			sqlgraph.To(billingcycle.Table, billingcycle.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, billing.BillingCycleTable, billing.BillingCycleColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Billing entity from the query.
// Returns a *NotFoundError when no Billing was found.
func (bq *BillingQuery) First(ctx context.Context) (*Billing, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{billing.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BillingQuery) FirstX(ctx context.Context) *Billing {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Billing ID from the query.
// Returns a *NotFoundError when no Billing ID was found.
func (bq *BillingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{billing.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BillingQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Billing entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Billing entity is found.
// Returns a *NotFoundError when no Billing entities are found.
func (bq *BillingQuery) Only(ctx context.Context) (*Billing, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{billing.Label}
	default:
		return nil, &NotSingularError{billing.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BillingQuery) OnlyX(ctx context.Context) *Billing {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Billing ID in the query.
// Returns a *NotSingularError when more than one Billing ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BillingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{billing.Label}
	default:
		err = &NotSingularError{billing.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BillingQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Billings.
func (bq *BillingQuery) All(ctx context.Context) ([]*Billing, error) {
	ctx = setContextOp(ctx, bq.ctx, "All")
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Billing, *BillingQuery]()
	return withInterceptors[[]*Billing](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BillingQuery) AllX(ctx context.Context) []*Billing {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Billing IDs.
func (bq *BillingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, "IDs")
	if err = bq.Select(billing.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BillingQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BillingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, "Count")
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BillingQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BillingQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BillingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, "Exist")
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BillingQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BillingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BillingQuery) Clone() *BillingQuery {
	if bq == nil {
		return nil
	}
	return &BillingQuery{
		config:           bq.config,
		ctx:              bq.ctx.Clone(),
		order:            append([]billing.OrderOption{}, bq.order...),
		inters:           append([]Interceptor{}, bq.inters...),
		predicates:       append([]predicate.Billing{}, bq.predicates...),
		withUser:         bq.withUser.Clone(),
		withBillingCycle: bq.withBillingCycle.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BillingQuery) WithUser(opts ...func(*UserQuery)) *BillingQuery {
	query := (&UserClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withUser = query
	return bq
}

// WithBillingCycle tells the query-builder to eager-load the nodes that are connected to
// the "billing_cycle" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BillingQuery) WithBillingCycle(opts ...func(*BillingCycleQuery)) *BillingQuery {
	query := (&BillingCycleClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withBillingCycle = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Billing.Query().
//		GroupBy(billing.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BillingQuery) GroupBy(field string, fields ...string) *BillingGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BillingGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = billing.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.Billing.Query().
//		Select(billing.FieldUUID).
//		Scan(ctx, &v)
func (bq *BillingQuery) Select(fields ...string) *BillingSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BillingSelect{BillingQuery: bq}
	sbuild.label = billing.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BillingSelect configured with the given aggregations.
func (bq *BillingQuery) Aggregate(fns ...AggregateFunc) *BillingSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BillingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !billing.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BillingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Billing, error) {
	var (
		nodes       = []*Billing{}
		withFKs     = bq.withFKs
		_spec       = bq.querySpec()
		loadedTypes = [2]bool{
			bq.withUser != nil,
			bq.withBillingCycle != nil,
		}
	)
	if bq.withUser != nil || bq.withBillingCycle != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, billing.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Billing).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Billing{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withUser; query != nil {
		if err := bq.loadUser(ctx, query, nodes, nil,
			func(n *Billing, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withBillingCycle; query != nil {
		if err := bq.loadBillingCycle(ctx, query, nodes, nil,
			func(n *Billing, e *BillingCycle) { n.Edges.BillingCycle = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BillingQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Billing, init func(*Billing), assign func(*Billing, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Billing)
	for i := range nodes {
		if nodes[i].billing_user == nil {
			continue
		}
		fk := *nodes[i].billing_user
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "billing_user" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BillingQuery) loadBillingCycle(ctx context.Context, query *BillingCycleQuery, nodes []*Billing, init func(*Billing), assign func(*Billing, *BillingCycle)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Billing)
	for i := range nodes {
		if nodes[i].billing_billing_cycle == nil {
			continue
		}
		fk := *nodes[i].billing_billing_cycle
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(billingcycle.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "billing_billing_cycle" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bq *BillingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BillingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(billing.Table, billing.Columns, sqlgraph.NewFieldSpec(billing.FieldID, field.TypeInt))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billing.FieldID)
		for i := range fields {
			if fields[i] != billing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BillingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(billing.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = billing.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BillingGroupBy is the group-by builder for Billing entities.
type BillingGroupBy struct {
	selector
	build *BillingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BillingGroupBy) Aggregate(fns ...AggregateFunc) *BillingGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BillingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, "GroupBy")
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillingQuery, *BillingGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BillingGroupBy) sqlScan(ctx context.Context, root *BillingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BillingSelect is the builder for selecting fields of Billing entities.
type BillingSelect struct {
	*BillingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BillingSelect) Aggregate(fns ...AggregateFunc) *BillingSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BillingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, "Select")
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillingQuery, *BillingSelect](ctx, bs.BillingQuery, bs, bs.inters, v)
}

func (bs *BillingSelect) sqlScan(ctx context.Context, root *BillingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
