// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrmnt/AA6_homework/billing/ent/billingcycle"
	"github.com/lrmnt/AA6_homework/billing/ent/predicate"
)

// BillingCycleQuery is the builder for querying BillingCycle entities.
type BillingCycleQuery struct {
	config
	ctx        *QueryContext
	order      []billingcycle.OrderOption
	inters     []Interceptor
	predicates []predicate.BillingCycle
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BillingCycleQuery builder.
func (bcq *BillingCycleQuery) Where(ps ...predicate.BillingCycle) *BillingCycleQuery {
	bcq.predicates = append(bcq.predicates, ps...)
	return bcq
}

// Limit the number of records to be returned by this query.
func (bcq *BillingCycleQuery) Limit(limit int) *BillingCycleQuery {
	bcq.ctx.Limit = &limit
	return bcq
}

// Offset to start from.
func (bcq *BillingCycleQuery) Offset(offset int) *BillingCycleQuery {
	bcq.ctx.Offset = &offset
	return bcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bcq *BillingCycleQuery) Unique(unique bool) *BillingCycleQuery {
	bcq.ctx.Unique = &unique
	return bcq
}

// Order specifies how the records should be ordered.
func (bcq *BillingCycleQuery) Order(o ...billingcycle.OrderOption) *BillingCycleQuery {
	bcq.order = append(bcq.order, o...)
	return bcq
}

// First returns the first BillingCycle entity from the query.
// Returns a *NotFoundError when no BillingCycle was found.
func (bcq *BillingCycleQuery) First(ctx context.Context) (*BillingCycle, error) {
	nodes, err := bcq.Limit(1).All(setContextOp(ctx, bcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{billingcycle.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bcq *BillingCycleQuery) FirstX(ctx context.Context) *BillingCycle {
	node, err := bcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BillingCycle ID from the query.
// Returns a *NotFoundError when no BillingCycle ID was found.
func (bcq *BillingCycleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bcq.Limit(1).IDs(setContextOp(ctx, bcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{billingcycle.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bcq *BillingCycleQuery) FirstIDX(ctx context.Context) int {
	id, err := bcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BillingCycle entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BillingCycle entity is found.
// Returns a *NotFoundError when no BillingCycle entities are found.
func (bcq *BillingCycleQuery) Only(ctx context.Context) (*BillingCycle, error) {
	nodes, err := bcq.Limit(2).All(setContextOp(ctx, bcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{billingcycle.Label}
	default:
		return nil, &NotSingularError{billingcycle.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bcq *BillingCycleQuery) OnlyX(ctx context.Context) *BillingCycle {
	node, err := bcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BillingCycle ID in the query.
// Returns a *NotSingularError when more than one BillingCycle ID is found.
// Returns a *NotFoundError when no entities are found.
func (bcq *BillingCycleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bcq.Limit(2).IDs(setContextOp(ctx, bcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{billingcycle.Label}
	default:
		err = &NotSingularError{billingcycle.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bcq *BillingCycleQuery) OnlyIDX(ctx context.Context) int {
	id, err := bcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BillingCycles.
func (bcq *BillingCycleQuery) All(ctx context.Context) ([]*BillingCycle, error) {
	ctx = setContextOp(ctx, bcq.ctx, "All")
	if err := bcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BillingCycle, *BillingCycleQuery]()
	return withInterceptors[[]*BillingCycle](ctx, bcq, qr, bcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bcq *BillingCycleQuery) AllX(ctx context.Context) []*BillingCycle {
	nodes, err := bcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BillingCycle IDs.
func (bcq *BillingCycleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bcq.ctx.Unique == nil && bcq.path != nil {
		bcq.Unique(true)
	}
	ctx = setContextOp(ctx, bcq.ctx, "IDs")
	if err = bcq.Select(billingcycle.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bcq *BillingCycleQuery) IDsX(ctx context.Context) []int {
	ids, err := bcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bcq *BillingCycleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bcq.ctx, "Count")
	if err := bcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bcq, querierCount[*BillingCycleQuery](), bcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bcq *BillingCycleQuery) CountX(ctx context.Context) int {
	count, err := bcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bcq *BillingCycleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bcq.ctx, "Exist")
	switch _, err := bcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bcq *BillingCycleQuery) ExistX(ctx context.Context) bool {
	exist, err := bcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BillingCycleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bcq *BillingCycleQuery) Clone() *BillingCycleQuery {
	if bcq == nil {
		return nil
	}
	return &BillingCycleQuery{
		config:     bcq.config,
		ctx:        bcq.ctx.Clone(),
		order:      append([]billingcycle.OrderOption{}, bcq.order...),
		inters:     append([]Interceptor{}, bcq.inters...),
		predicates: append([]predicate.BillingCycle{}, bcq.predicates...),
		// clone intermediate query.
		sql:  bcq.sql.Clone(),
		path: bcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BillingCycle.Query().
//		GroupBy(billingcycle.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bcq *BillingCycleQuery) GroupBy(field string, fields ...string) *BillingCycleGroupBy {
	bcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BillingCycleGroupBy{build: bcq}
	grbuild.flds = &bcq.ctx.Fields
	grbuild.label = billingcycle.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.BillingCycle.Query().
//		Select(billingcycle.FieldUUID).
//		Scan(ctx, &v)
func (bcq *BillingCycleQuery) Select(fields ...string) *BillingCycleSelect {
	bcq.ctx.Fields = append(bcq.ctx.Fields, fields...)
	sbuild := &BillingCycleSelect{BillingCycleQuery: bcq}
	sbuild.label = billingcycle.Label
	sbuild.flds, sbuild.scan = &bcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BillingCycleSelect configured with the given aggregations.
func (bcq *BillingCycleQuery) Aggregate(fns ...AggregateFunc) *BillingCycleSelect {
	return bcq.Select().Aggregate(fns...)
}

func (bcq *BillingCycleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bcq); err != nil {
				return err
			}
		}
	}
	for _, f := range bcq.ctx.Fields {
		if !billingcycle.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bcq.path != nil {
		prev, err := bcq.path(ctx)
		if err != nil {
			return err
		}
		bcq.sql = prev
	}
	return nil
}

func (bcq *BillingCycleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BillingCycle, error) {
	var (
		nodes = []*BillingCycle{}
		_spec = bcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BillingCycle).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BillingCycle{config: bcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (bcq *BillingCycleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bcq.querySpec()
	_spec.Node.Columns = bcq.ctx.Fields
	if len(bcq.ctx.Fields) > 0 {
		_spec.Unique = bcq.ctx.Unique != nil && *bcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bcq.driver, _spec)
}

func (bcq *BillingCycleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(billingcycle.Table, billingcycle.Columns, sqlgraph.NewFieldSpec(billingcycle.FieldID, field.TypeInt))
	_spec.From = bcq.sql
	if unique := bcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bcq.path != nil {
		_spec.Unique = true
	}
	if fields := bcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billingcycle.FieldID)
		for i := range fields {
			if fields[i] != billingcycle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bcq *BillingCycleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bcq.driver.Dialect())
	t1 := builder.Table(billingcycle.Table)
	columns := bcq.ctx.Fields
	if len(columns) == 0 {
		columns = billingcycle.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bcq.sql != nil {
		selector = bcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bcq.ctx.Unique != nil && *bcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bcq.predicates {
		p(selector)
	}
	for _, p := range bcq.order {
		p(selector)
	}
	if offset := bcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BillingCycleGroupBy is the group-by builder for BillingCycle entities.
type BillingCycleGroupBy struct {
	selector
	build *BillingCycleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bcgb *BillingCycleGroupBy) Aggregate(fns ...AggregateFunc) *BillingCycleGroupBy {
	bcgb.fns = append(bcgb.fns, fns...)
	return bcgb
}

// Scan applies the selector query and scans the result into the given value.
func (bcgb *BillingCycleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bcgb.build.ctx, "GroupBy")
	if err := bcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillingCycleQuery, *BillingCycleGroupBy](ctx, bcgb.build, bcgb, bcgb.build.inters, v)
}

func (bcgb *BillingCycleGroupBy) sqlScan(ctx context.Context, root *BillingCycleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bcgb.fns))
	for _, fn := range bcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bcgb.flds)+len(bcgb.fns))
		for _, f := range *bcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BillingCycleSelect is the builder for selecting fields of BillingCycle entities.
type BillingCycleSelect struct {
	*BillingCycleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bcs *BillingCycleSelect) Aggregate(fns ...AggregateFunc) *BillingCycleSelect {
	bcs.fns = append(bcs.fns, fns...)
	return bcs
}

// Scan applies the selector query and scans the result into the given value.
func (bcs *BillingCycleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bcs.ctx, "Select")
	if err := bcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BillingCycleQuery, *BillingCycleSelect](ctx, bcs.BillingCycleQuery, bcs, bcs.inters, v)
}

func (bcs *BillingCycleSelect) sqlScan(ctx context.Context, root *BillingCycleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bcs.fns))
	for _, fn := range bcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
