// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/lrmnt/AA6_homework/billing/ent/schema"
	"github.com/lrmnt/AA6_homework/billing/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[3].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(int64)
}
