proto:
	protoc --go_out=paths=source_relative:. api/schema/task_event/task_event.proto
	protoc --go_out=paths=source_relative:. api/schema/task_stream/task_stream.proto
	protoc --go_out=paths=source_relative:. api/schema/user_stream/user_stream.proto
	protoc --go_out=paths=source_relative:. api/schema/billing_event/billing_event.proto