// Code generated by ent, DO NOT EDIT.

package userlog

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userlog type in the database.
	Label = "user_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// Table holds the table name of the userlog in the database.
	Table = "user_logs"
)

// Columns holds all SQL columns for userlog fields.
var Columns = []string{
	FieldID,
	FieldIdempotencyKey,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UserLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}
