// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lrmnt/AA6_homework/tasks/ent/userlog"
)

// UserLog is the model entity for the UserLog schema.
type UserLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userlog.FieldID:
			values[i] = new(sql.NullInt64)
		case userlog.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserLog fields.
func (ul *UserLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ul.ID = int(value.Int64)
		case userlog.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				ul.IdempotencyKey = value.String
			}
		default:
			ul.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserLog.
// This includes values selected through modifiers, order, etc.
func (ul *UserLog) Value(name string) (ent.Value, error) {
	return ul.selectValues.Get(name)
}

// Update returns a builder for updating this UserLog.
// Note that you need to call UserLog.Unwrap() before calling this method if this UserLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (ul *UserLog) Update() *UserLogUpdateOne {
	return NewUserLogClient(ul.config).UpdateOne(ul)
}

// Unwrap unwraps the UserLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ul *UserLog) Unwrap() *UserLog {
	_tx, ok := ul.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserLog is not a transactional entity")
	}
	ul.config.driver = _tx.drv
	return ul
}

// String implements the fmt.Stringer.
func (ul *UserLog) String() string {
	var builder strings.Builder
	builder.WriteString("UserLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ul.ID))
	builder.WriteString("idempotency_key=")
	builder.WriteString(ul.IdempotencyKey)
	builder.WriteByte(')')
	return builder.String()
}

// UserLogs is a parsable slice of UserLog.
type UserLogs []*UserLog
