// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrmnt/AA6_homework/tasks/ent/predicate"
	"github.com/lrmnt/AA6_homework/tasks/ent/userlog"
)

// UserLogQuery is the builder for querying UserLog entities.
type UserLogQuery struct {
	config
	ctx        *QueryContext
	order      []userlog.OrderOption
	inters     []Interceptor
	predicates []predicate.UserLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserLogQuery builder.
func (ulq *UserLogQuery) Where(ps ...predicate.UserLog) *UserLogQuery {
	ulq.predicates = append(ulq.predicates, ps...)
	return ulq
}

// Limit the number of records to be returned by this query.
func (ulq *UserLogQuery) Limit(limit int) *UserLogQuery {
	ulq.ctx.Limit = &limit
	return ulq
}

// Offset to start from.
func (ulq *UserLogQuery) Offset(offset int) *UserLogQuery {
	ulq.ctx.Offset = &offset
	return ulq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ulq *UserLogQuery) Unique(unique bool) *UserLogQuery {
	ulq.ctx.Unique = &unique
	return ulq
}

// Order specifies how the records should be ordered.
func (ulq *UserLogQuery) Order(o ...userlog.OrderOption) *UserLogQuery {
	ulq.order = append(ulq.order, o...)
	return ulq
}

// First returns the first UserLog entity from the query.
// Returns a *NotFoundError when no UserLog was found.
func (ulq *UserLogQuery) First(ctx context.Context) (*UserLog, error) {
	nodes, err := ulq.Limit(1).All(setContextOp(ctx, ulq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ulq *UserLogQuery) FirstX(ctx context.Context) *UserLog {
	node, err := ulq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserLog ID from the query.
// Returns a *NotFoundError when no UserLog ID was found.
func (ulq *UserLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulq.Limit(1).IDs(setContextOp(ctx, ulq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ulq *UserLogQuery) FirstIDX(ctx context.Context) int {
	id, err := ulq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserLog entity is found.
// Returns a *NotFoundError when no UserLog entities are found.
func (ulq *UserLogQuery) Only(ctx context.Context) (*UserLog, error) {
	nodes, err := ulq.Limit(2).All(setContextOp(ctx, ulq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userlog.Label}
	default:
		return nil, &NotSingularError{userlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ulq *UserLogQuery) OnlyX(ctx context.Context) *UserLog {
	node, err := ulq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserLog ID in the query.
// Returns a *NotSingularError when more than one UserLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (ulq *UserLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulq.Limit(2).IDs(setContextOp(ctx, ulq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userlog.Label}
	default:
		err = &NotSingularError{userlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ulq *UserLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := ulq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserLogs.
func (ulq *UserLogQuery) All(ctx context.Context) ([]*UserLog, error) {
	ctx = setContextOp(ctx, ulq.ctx, "All")
	if err := ulq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserLog, *UserLogQuery]()
	return withInterceptors[[]*UserLog](ctx, ulq, qr, ulq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ulq *UserLogQuery) AllX(ctx context.Context) []*UserLog {
	nodes, err := ulq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserLog IDs.
func (ulq *UserLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ulq.ctx.Unique == nil && ulq.path != nil {
		ulq.Unique(true)
	}
	ctx = setContextOp(ctx, ulq.ctx, "IDs")
	if err = ulq.Select(userlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ulq *UserLogQuery) IDsX(ctx context.Context) []int {
	ids, err := ulq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ulq *UserLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ulq.ctx, "Count")
	if err := ulq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ulq, querierCount[*UserLogQuery](), ulq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ulq *UserLogQuery) CountX(ctx context.Context) int {
	count, err := ulq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ulq *UserLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ulq.ctx, "Exist")
	switch _, err := ulq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ulq *UserLogQuery) ExistX(ctx context.Context) bool {
	exist, err := ulq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ulq *UserLogQuery) Clone() *UserLogQuery {
	if ulq == nil {
		return nil
	}
	return &UserLogQuery{
		config:     ulq.config,
		ctx:        ulq.ctx.Clone(),
		order:      append([]userlog.OrderOption{}, ulq.order...),
		inters:     append([]Interceptor{}, ulq.inters...),
		predicates: append([]predicate.UserLog{}, ulq.predicates...),
		// clone intermediate query.
		sql:  ulq.sql.Clone(),
		path: ulq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IdempotencyKey string `json:"idempotency_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserLog.Query().
//		GroupBy(userlog.FieldIdempotencyKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ulq *UserLogQuery) GroupBy(field string, fields ...string) *UserLogGroupBy {
	ulq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserLogGroupBy{build: ulq}
	grbuild.flds = &ulq.ctx.Fields
	grbuild.label = userlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IdempotencyKey string `json:"idempotency_key,omitempty"`
//	}
//
//	client.UserLog.Query().
//		Select(userlog.FieldIdempotencyKey).
//		Scan(ctx, &v)
func (ulq *UserLogQuery) Select(fields ...string) *UserLogSelect {
	ulq.ctx.Fields = append(ulq.ctx.Fields, fields...)
	sbuild := &UserLogSelect{UserLogQuery: ulq}
	sbuild.label = userlog.Label
	sbuild.flds, sbuild.scan = &ulq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserLogSelect configured with the given aggregations.
func (ulq *UserLogQuery) Aggregate(fns ...AggregateFunc) *UserLogSelect {
	return ulq.Select().Aggregate(fns...)
}

func (ulq *UserLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ulq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ulq); err != nil {
				return err
			}
		}
	}
	for _, f := range ulq.ctx.Fields {
		if !userlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ulq.path != nil {
		prev, err := ulq.path(ctx)
		if err != nil {
			return err
		}
		ulq.sql = prev
	}
	return nil
}

func (ulq *UserLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserLog, error) {
	var (
		nodes = []*UserLog{}
		_spec = ulq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserLog{config: ulq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ulq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ulq *UserLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ulq.querySpec()
	_spec.Node.Columns = ulq.ctx.Fields
	if len(ulq.ctx.Fields) > 0 {
		_spec.Unique = ulq.ctx.Unique != nil && *ulq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ulq.driver, _spec)
}

func (ulq *UserLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userlog.Table, userlog.Columns, sqlgraph.NewFieldSpec(userlog.FieldID, field.TypeInt))
	_spec.From = ulq.sql
	if unique := ulq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ulq.path != nil {
		_spec.Unique = true
	}
	if fields := ulq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userlog.FieldID)
		for i := range fields {
			if fields[i] != userlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ulq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ulq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ulq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ulq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ulq *UserLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ulq.driver.Dialect())
	t1 := builder.Table(userlog.Table)
	columns := ulq.ctx.Fields
	if len(columns) == 0 {
		columns = userlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ulq.sql != nil {
		selector = ulq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ulq.ctx.Unique != nil && *ulq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ulq.predicates {
		p(selector)
	}
	for _, p := range ulq.order {
		p(selector)
	}
	if offset := ulq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ulq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserLogGroupBy is the group-by builder for UserLog entities.
type UserLogGroupBy struct {
	selector
	build *UserLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ulgb *UserLogGroupBy) Aggregate(fns ...AggregateFunc) *UserLogGroupBy {
	ulgb.fns = append(ulgb.fns, fns...)
	return ulgb
}

// Scan applies the selector query and scans the result into the given value.
func (ulgb *UserLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulgb.build.ctx, "GroupBy")
	if err := ulgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserLogQuery, *UserLogGroupBy](ctx, ulgb.build, ulgb, ulgb.build.inters, v)
}

func (ulgb *UserLogGroupBy) sqlScan(ctx context.Context, root *UserLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ulgb.fns))
	for _, fn := range ulgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ulgb.flds)+len(ulgb.fns))
		for _, f := range *ulgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ulgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserLogSelect is the builder for selecting fields of UserLog entities.
type UserLogSelect struct {
	*UserLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uls *UserLogSelect) Aggregate(fns ...AggregateFunc) *UserLogSelect {
	uls.fns = append(uls.fns, fns...)
	return uls
}

// Scan applies the selector query and scans the result into the given value.
func (uls *UserLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uls.ctx, "Select")
	if err := uls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserLogQuery, *UserLogSelect](ctx, uls.UserLogQuery, uls, uls.inters, v)
}

func (uls *UserLogSelect) sqlScan(ctx context.Context, root *UserLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uls.fns))
	for _, fn := range uls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
