// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Billing is the predicate function for billing builders.
type Billing func(*sql.Selector)

// BillingCycle is the predicate function for billingcycle builders.
type BillingCycle func(*sql.Selector)

// Operations is the predicate function for operations builders.
type Operations func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskLog is the predicate function for tasklog builders.
type TaskLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserLog is the predicate function for userlog builders.
type UserLog func(*sql.Selector)
